config/routes.rb
Rails.application.routes.draw do
      root 'static_pages#home'
      get  '/help',    to: 'static_pages#help'
      get  '/about',   to: 'static_pages#about'
      get  '/contact', to: 'static_pages#contact'
      get  '/signup',  to: 'users#new'
      resources :users 

            get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      delete '/logout',  to: 'sessions#destroy'

       resources :microposts, only: [:create, :destroy] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
 class Micropost < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 140 }
  end

app/models/user.rb
class User < ApplicationRecord

	 attr_accessor :remember_token       # NEW LINE


	has_many :microposts, dependent: :destroy

     before_save { self.email = email.downcase }
     validates :name, presence: true, length: { in: 9..30 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
      validates :password, presence: true, length: { minimum: 6 }
      has_secure_password


      
       # ALL NEW METHODS
          def User.digest(string)
            cost = ActiveModel::SecurePassword.min_cost ?    
                        BCrypt::Engine::MIN_COST :
                        BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
          end

          def User.new_token
            SecureRandom.urlsafe_base64
          end

          def remember
            self.remember_token = User.new_token
            update_attribute(:remember_digest, 
                        User.digest(remember_token))
          end

          def authenticated?(remember_token)
            BCrypt::Password.new(remember_digest).is_password?(remember_token)
          end 

           def forget
              update_attribute(:remember_digest, nil)
           end  

       def feed
        Micropost.where("user_id = ?", id)
      end  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  include SessionsHelper 

end

app/controllers/micropostss_controller.rb
 class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy 

    def create
         secure_post = params.require(:micropost).permit(:content)
      @micropost = current_user.microposts.build(secure_post) 
      if @micropost.save
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        @feed_items = [] 
        render 'static_pages/home'
      end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to root_url    
    end

    private

      def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end 
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
             def new
            end

            def create
               user = User.find_by(email: params[:session][:email].downcase)
                if user && user.authenticate(params[:session][:password])
                   remember user  
                   redirect_to user 
                else
                  flash.now[:danger] = 'Invalid email/password combination'
                  render 'new'
                end
              end

              def destroy
                log_out if logged_in?
                redirect_to root_url
              end          
        end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   if logged_in?
        @micropost  = current_user.microposts.build
        @feed_items = current_user.feed
     end
   end

  def help
  end

  def about      # NEW
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
     @user = User.find(params[:id])
     @microposts = @user.microposts 
  end

  def new
      @user = User.new
  end

  def create
     secure_params = params.require(:user).permit(:name, :email, 
                                  :password, :password_confirmation)
     @user = User.new(secure_params)
     if @user.save
        remember @user           # NEW LINE
        flash[:success] = "Welcome to the Twitter App!" 
        redirect_to @user 
     else
        render 'new' 
     end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

          def remember(user)
            user.remember
            cookies.permanent.signed[:user_id] = user.id
            cookies.permanent[:remember_token] = user.remember_token
          end

          def current_user
            if (user_id = cookies.signed[:user_id])
               user = User.find_by(id: user_id)
               if user && 
                    user.authenticated?(cookies[:remember_token])
                  @current_user = user
               end
            end
          end

          def logged_in?
            !current_user.nil?
          end

          def current_user?(user)
            user == current_user
          end  

          def forget(user)
              user.forget
              cookies.delete(:user_id)
              cookies.delete(:remember_token)
          end

          def log_out
              forget(current_user)
              @current_user = nil
          end
          def logged_in_user
            unless logged_in?
            flash[:notice] = "Please log in"
            redirect_to login_url
            end
          end   
    end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
 module UsersHelper

     def gravatar_for(user, options = { size: 50 })
         gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
         image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 
   end

app/views/layouts/_footer.html.erb
  <footer class="footer">
      <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
      </nav>
    </footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
           <div class="container">
             <%= link_to "sample app", root_path, id: "logo" %>
             <nav>
               <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <% if logged_in? %>
                  <li><%= link_to "Users", '#' %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", '#' %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                <% end %>
               </ul>
             </nav>
           </div>
        </header>

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
      <head>
        <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                                  'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
      </head>
      <body>
        <%= render 'layouts/header' %> 
        <div class="container">
           <% flash.each do |message_type, message| %> 
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>  
          <%= yield %>
          <%= render 'layouts/footer' %> 
          <%= debug(params) if Rails.env.development? %>
     </div>
        </div>
      </body>
    </html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
         <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete,
                                             data: { confirm: "You sure?" } %>
          <% end %>
    </span>
  </li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
       <div id="error_explanation">
         <div class="alert alert-danger">
          The form contains <%= pluralize(object.errors.count, "error") %>.
         </div>
         <ul>
        <% object.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
          </div>
       <% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
      <ol class="microposts">
        <%= render @feed_items %>
      </ol>
    <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
      </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
    <h1><%= current_user.name %></h1>
    <span><%= link_to "view my profile", current_user %></span>
    <span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
   <% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/static_pages/help.html.erb
   <% provide(:title, 'Help') %>
  <h1>Help</h1>
  <p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
  </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
 <% if logged_in? %>
     <div class="row">
        <aside class="col-md-4">
          <section class="user_info">
            <%= render 'shared/user_info' %>
          </section>
          <section class="micropost_form">
            <%= render 'shared/micropost_form' %>
          </section>
        </aside>
        <div class="col-md-8">
          <h3>Micropost Feed</h3>
          <%= render 'shared/feed' %>
        </div>
      </div>
<% else %>
    <div class="center jumbotron">
   <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>

app/views/users/new.html.erb
 <% provide(:title, 'Sign up') %>
    <h1>Sign up</h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

app/views/users/show.html.erb
 <% provide(:title, @user.name) %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
          </h1>
        </section>
      </aside>
      <div class="col-md-8">
        <% if @user.microposts.any? %>
          <h3>Microposts (<%= @user.microposts.count %>)</h3>
          <ol class="microposts">
            <%= render @microposts %>
          </ol>
        <% end %>
      </div>
    </div>